### ISSUE TITLE
Usage of `effect`

### ISSUE THREAD

**Issue by yyx990803** [Planning-nl/vugel#1]
This is picking up from https://github.com/vuejs/rfcs/issues/157#issuecomment-614112417

I think I misunderstood how you intend to ship your library, assuming your renderer is not used alongside the normal Vue runtime. But it seems Vugel can be used directly inside a normal Vue application (which is great!).

In that case it seems we do need to expose `effect` - however that kinda brings in another issue: [the wrapper is using `effect` without a scheduler](https://github.com/Planning-nl/vugel/blob/master/src/wrapper.ts#L38), which means the effect will run synchronously whenever any property change is detected (i.e. `state.foo = 1; state.foo = 2` will result in 2 consecutive updates). Is that intended?

Internally Vue uses a scheduler to buffer the updates, ensure component update order, dedupe, invalidation etc. If `effect` is used in this manner we may need to expose `queueJob` as well for custom renderers.

**Comment by yyx990803** [comment]
I think `watchEffect` in `onMounted` should just work and you don't really need to overwrite `instance.update`.

**Comment by yyx990803** [comment]
I just tested using `watchEffect(...)` instead of `instance.update = effect(...)` and it seems to work as intended in the example. I think there should be no need to expose `effect` (and therefore `queueJob`) in this case.

**Comment by RobbinBaauw** [comment]
Thanks for this research! We will change this accordingly :)
